(define (adj*)
  (if (= (random 2) 0)
      '()
      (append (adj) (adj*))))
(define (pp*)
  (if (random-elt '(#t #f))
      (append (pp) (pp*))
      '()))
(define (noun-phrase)
  (append (article) (adj*) (noun) (pp*)))
(define (pp)
  (append (prep) (noun-phrase)))
(define (adj)
  (one-of '(big little blue green adiabatic)))
(define (prep)
  (one-of '(to in by with on)))
(define (article)
  (one-of '(the a)))
(define (noun) (one-of '(man ball woman table)))
(define (one-of lst)
  (list (random-elt lst)))
(define (random-elt lst)
  (list-ref lst (random (length lst))))
