(define (sentence)
  (append (noun-phrase) (verb-phrase)))
(define (noun-phrase)
  (append (article) (noun)))
(define (verb-phrase)
  (append (verb) (noun-phrase)))
(define (article) (one-of '(the a)))
(define (noun) (one-of '(man ball woman table)))
(define (verb) (one-of '(hit took saw liked)))
(define (one-of lst)
  (list (random-elt lst)))
(define (random-elt lst)
  (list-ref lst (random (length lst))))
